### ISSUE TITLE
`file_name_as_title: true` doesn't seem to work

### ISSUE THREAD

**Issue by Acentelles** [mysiki/mkdocs_include_dir_to_nav#1]
Tried 
```
    - include_dir_to_nav:
        file_name_as_title: true
```

but I still see the header of the file content as title, instead of the file name.

Also would it be possible to order them lexicographically?

Thank you

**Comment by mysiki** [comment]
Hello, i will check it this week.

I will also check for order option.

**Comment by mysiki** [comment]
Hello,

I confirm than file_name_as_title work : 

result without : 

```yaml
- zzfolder:
  - apage: fold_sort/zzfolder/apage.md
  - zpage: fold_sort/zzfolder/zpage.md
```

result with : 

```yaml
- zzfolder:
  - fold_sort/zzfolder/apage.md
  - fold_sort/zzfolder/zpage.md
```

With file_name_as_title , we force nav menu to used file name in key entry. 

For order options, I have add sort folder, sort file and reverse mode.
